version: '3.8'

services:
  app:
    build: 
      context: ..
      dockerfile: docker/Dockerfile.dev  
    container_name: fiber-mvc-api-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ../env/.env.example
    volumes:
      - ../:/app
      - ../.air.toml:/app/.air.toml  
      
    # depends_on:
    #   postgres:
    #     condition: service_healthy
    networks:
      - fiber-network

  # postgres:
  #   image: postgres:15-alpine
  #   container_name: fiber-postgres-dev
  #   restart: unless-stopped
  #   environment:
  #     - POSTGRES_USER=fiber_user
  #     - POSTGRES_PASSWORD=fiber_password
  #     - POSTGRES_DB=fiber_db
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_dev_data:/var/lib/postgresql/data
  #   networks:
  #     - fiber-network
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U fiber_user -d fiber_db"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

networks:
  fiber-network:
    driver: bridge

# volumes:
#   postgres_dev_data:
#     driver: local
