basePath: /api/v1
definitions:
  response.SWErrorDetail:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
  response.SWErrorResponse:
    properties:
      data: {}
      error:
        $ref: '#/definitions/response.SWErrorDetail'
      success:
        example: false
        type: boolean
    type: object
  response.SWListDataDetail:
    properties:
      data:
        items:
          type: object
        type: array
      limit:
        type: integer
      page:
        type: integer
      total:
        type: integer
    type: object
  response.SWListSuccessResponse:
    properties:
      data:
        $ref: '#/definitions/response.SWListDataDetail'
      error:
        type: object
      success:
        example: true
        type: boolean
    type: object
  response.SWSuccessResponse:
    properties:
      data:
        type: object
      error:
        type: object
      success:
        example: true
        type: boolean
    type: object
info:
  contact: {}
  description: This is a sample API GoFiber application.
  title: My API
  version: 0.1.1
paths:
  /users:
    get:
      description: Retrieve all users from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SWListSuccessResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.SWErrorResponse'
      security:
      - BearerAuth: []
      summary: Get all users
      tags:
      - Users
  /users/{id}:
    get:
      description: Retrieve all users from the database
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SWSuccessResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.SWErrorResponse'
      security:
      - BearerAuth: []
      summary: Get user by ID
      tags:
      - Users
securityDefinitions:
  ApiKeyAuth:
    description: Provide your API key in the 'X-API-Key' header.
    in: header
    name: X-API-Key
    type: apiKey
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
